export default function getAllProducts() {
  return [
    {
      id: 'HS-APT-1-07-HOUSE-001',
      slug: 'apartment-jkt-living-star',
      name: 'International Eco-Apartment JKT Living Star',
      category: 'House',
      categorySlug: 'house',
      price: 950_571_000,
      stock: 100,
      imageUrl: 'assets/img/1home.jpg',
      description: `JKT Living Star is a contemporary apartment complex situated in the heart of Jakarta, providing convenient access to urban conveniences. The aesthetic appeal and functional design of the complex include a variety of unit types, well-suited for families and young professionals.
                        Each unit is furnished with high-quality items and features large windows that allow for the entry of natural light. Residents have access to a swimming pool, a gym, and green spaces, conducive to relaxation. The complex is situated in a location that is convenient for shopping, dining, and public transportation,
                        making it an ideal choice for individuals who desire a vibrant urban lifestyle. Additionally, the complex provides 24-hour security and attentive service, which contribute to a comfortable and secure living experience.`,
    },
    {
      id: 'HS-LVT-5-CGJ-002',
      slug: 'lavia-living-type-5-citra-garden-city-jakarta',
      name: 'Lavia Living Type 5 at Citra Garden City Jakarta',
      category: 'House',
      categorySlug: 'house',
      price: 2_186_313_300,
      stock: 5,
      imageUrl: '/assets/img/2home.jpg',
      description: `The Lavia Living Type 5 in Citra Garden City, Jakarta, is a modern residence designed for comfort and functionality. With a land area of 60 m² and a building area of 95 m², it features four bedrooms and three bathrooms, making it ideal for families. The stylish interior, crafted from high-quality materials, creates a warm atmosphere.
                    Citra Garden City is known for its aesthetic appeal and extensive amenities, including green spaces and convenient access to shopping and transport. The residence is equipped with an advanced security system, ensuring the safety of its occupants. Overall, Lavia Living Type 5 is an excellent choice for quality housing in Jakarta.`,
    },
    {
      id: 'HS-AVN-SH-003',
      slug: 'avilla-nova-cluster-samanea-hill',
      name: 'Avilla Nova Cluster at Samanea Hill',
      category: 'House',
      categorySlug: 'house',
      price: 1_017_111_000,
      stock: 5,
      imageUrl: '/assets/img/3home.jpg',
      description: `The Avilla Nova cluster at Samanea Hill is a modern residential development that blends comfort with aesthetic appeal. It features various architectural styles designed for families, with spacious interiors and abundant natural light, enhanced by premium materials.
                    Located strategically, Samanea Hill offers easy access to shopping centers, schools, and recreational areas. Surrounded by lush green parks, the cluster provides a tranquil atmosphere. With a secure environment and a friendly community, Avilla Nova is an excellent choice for quality housing in a thriving area.`,
    },
    {
      id: 'HS-QST-178-BSD-004',
      slug: 'quantis-signature-type-178-bsd-city',
      name: 'Quantis Signature Type 178 at BSD City',
      category: 'House',
      categorySlug: 'house',
      price: 8_150_659_350,
      stock: 5,
      imageUrl: '/assets/img/4home.jpg',
      description: `The Quantis Signature Type 178 in BSD City is a modern residence tailored for families. With a built-up area of 178 m², it features three bedrooms and two bathrooms, ensuring spacious and comfortable living. The sophisticated interior and high-quality materials create a warm atmosphere.
                    Located in the rapidly developing BSD City, the home offers easy access to shopping, schools, and recreational facilities. Its attractive, secure environment, supported by a robust security system, makes Quantis Signature Type 178 an excellent choice for those seeking a premium residence in a vibrant urban setting.`,
    },

    {
      id: 'MT-BMBP-001',
      slug: 'bamboo-petung-dendrocalamus-asper',
      name: 'Bamboo Petung (Dendrocalamus asper)',
      category: 'Material',
      categorySlug: 'material',
      price: 4_199_850,
      stock: 0,
      imageUrl: '/assets/img/image 40.png',
      description: `Bamboo Petung (Dendrocalamus asper) is an optimal choice for those who prioritize sustainability and environmental responsibility. As one of the largest and strongest bamboos, Bamboo Petung offers exceptional strength, durability, and the ability to be harvested sustainably. Its rapid growth also makes it an ideal choice for construction, furniture, and decoration projects. By using Bamboo Petung, you can support eco-friendly practices that reduce deforestation and carbon emissions.`,
    },
    {
      id: 'MT-EIKO-002',
      slug: 'eiken-oak-tongue-and-groove',
      name: 'Eiken (Oak) - Tongue and Groove',
      category: 'Material',
      categorySlug: 'material',
      price: 24_886_650,
      stock: 0,
      imageUrl: '/assets/img/image 52.png',
      description: `Eiken (Oak) - Tongue and Groove is the optimal choice for those seeking natural beauty and exceptional durability in their building projects. This oak offers an elegant aesthetic with a tongue and groove system that ensures easy and sturdy installation, and it is sourced from a sustainably managed source. By selecting Eiken (Oak), you are supporting environmentally friendly practices that help preserve forests and reduce carbon footprints. Additionally, oak is renowned for its high resistance to wear and tear, making it an optimal choice for long-lasting flooring and wall panels. Make Eiken (Oak) - Tongue and Groove part of your green solution for your home or project, and enjoy the long-term benefits of this high-quality material.`,
    },
    {
      id: 'MT-BSTR-003',
      slug: 'basalt-rock-material',
      name: 'Basaltic (Fine-Grained) Rock',
      category: 'Material',
      categorySlug: 'material',
      price: 1_909_000,
      stock: 0,
      imageUrl: '/assets/img/image 58.png',
      description: `Basalt rock is the optimal choice for your construction projects that require exceptional strength and durability. Formed from natural volcanic processes, this rock has a dense and hard structure, making it highly resistant to pressure and erosion. Additionally, basalt rock is an eco-friendly material, derived from an abundant and renewable natural resource. By choosing basalt rock, you are not only getting a durable and strong material, but also contributing to the preservation of the environment. Make basalt rock a part of your construction solution for optimal and sustainable results.`,
    },
    {
      id: 'MT-PVBL-004',
      slug: 'paving-block-material',
      name: 'Plastic Waste Recycling Paving Block ',
      category: 'Material',
      categorySlug: 'material',
      price: 1_909_000,
      stock: 0,
      imageUrl: '/assets/img/material4_besar.jpg',
      description: `Paving blocks are a great option for landscaping and road projects that need to stand up to a lot of wear and tear and look good doing it. Made from a high-quality concrete mix, paving blocks are strong and can handle heavy loads and extreme weather. Plus, paving blocks come in all kinds of designs and colors, so you can get the look you want. They're also eco-friendly because you can recycle them and they reduce construction waste. When you choose paving blocks, you get a durable and attractive solution that's good for the planet. Make paving blocks part of your construction solution for the best and greenest results.`,
    },
  ];
}
